version: 2

defaults: &defaults
  working_directory: ~/vue-styleguidist
  docker:
    - image: circleci/node:lts

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-vue-styleguidist-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: v1-vue-styleguidist-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
            - ~/.cache
      - persist_to_workspace:
          root: ~/
  compile:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn compile
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn lint
      - run: yarn test
      - run: yarn danger ci 
workflows:
  version: 2