version: 2

defaults: &defaults
  docker:
    - image: circleci/node:lts
  working_directory: ~/vue-styleguidist

jobs:
  install:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-vue-styleguidist-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: v1-vue-styleguidist-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/
          paths:
            - vue-styleguidist

  compile:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la
      - run: yarn compile
      - persist_to_workspace:
          root: packages/
          paths:
            - vue-styleguidist/dist/*
            - vue-styleguidist/lib/*

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn lint
      - run: yarn test
      - run: yarn danger ci

  integration:
    <<: *defaults
    steps:
      - attach_workspace:
          at: packages/

      # Build all examples
      - run: yarn build basic
      - run: yarn build customised
      - run: yarn build sections
      - run: yarn build vuex
      - run: yarn build jsx
      - run: yarn build nuxtjs/styleguide
      - run: yarn build vuetify
      - run: yarn build vuecli-noplugin
      - run: yarn build:vuecli3

      # Check that examples really works: no JS errors on load
      - run: yarn test:browser basic
      - run: yarn test:browser customised
      - run: yarn test:browser sections
      - run: yarn test:browser vuex
      - run: yarn test:browser jsx
      - run: yarn test:browser nuxtjs
      - run: yarn test:browser vuetify
      - run: yarn test:browser vuecli-noplugin
      - run: yarn test:browser vuecli3
workflows:
  version: 2
  test:
    jobs:
      - install
      - compile:
          requires:
            - install
      - test:
          requires:
            - compile
      - integration:
          requires:
            - compile
